#!/bin/bash
nohup python3 /root/domen_checker.py &
nohup python3 /root/NewAppsBot.py &
nohup python3 /root/CabShareBot.py &
nohup python3 /root/Unikalizator.py &
nohup python3 /root/Aprove_bot.py &
nohup python3 /root/Rico_bot_v3.0/Main.py &
nohup python3 /root/pushbot/apps/CoinMonster.py &
nohup python3 /root/pushbot/apps/CoinMystery.py &
nohup python3 /root/pushbot/apps/DiamondHall.py &
nohup python3 /root/pushbot/apps/FruitSpin.py &
nohup python3 /root/pushbot/apps/NewEra.py &
nohup python3 /root/pushbot/apps/VegasQueen.py &
nohup python3 /root/pushbot/apps/NetworkScanner.py &
nohup python3 /root/pushbot/apps/ScreenRecorder.py &
nohup python3 /root/pushbot/apps/KingOfSpin.py &
nohup python3 /root/pushbot/apps/TheDarkPrince.py &
nohup python3 /root/pushbot/apps/AncientMystery.py &
nohup python3 /root/pushbot/apps/RainbowCoins.py &
nohup python3 /root/pushbot/apps/OceanSecret.py &
nohup python3 /root/pushbot/apps/MerlinWizard.py &
nohup python3 /root/pushbot/apps/EastAbundance.py &
nohup python3 /root/pushbot/apps/ZeusEmpire.py &
nohup python3 /root/pushbot/apps/JokerofGG.py &
nohup python3 /root/pushbot/apps/JokerLocker.py &
nohup python3 /root/pushbot/apps/JokerOfGold.py &
nohup python3 /root/pushbot/apps/TotemsHistory.py &
nohup python3 /root/pushbot/apps/DragonDices.py &
nohup python3 /root/pushbot/apps/PlaceofLuck.py &
nohup python3 /root/pushbot/apps/Retrowave.py &
nohup python3 /root/pushbot/apps/WonderfullMiracles.py &
nohup python3 /root/pushbot/apps/WheelFortune.py &
nohup python3 /root/pushbot/apps/BonusMachine.py &
nohup python3 /root/pushbot/apps/GoldRunner.py &
nohup python3 /root/pushbot/apps/WinClub.py &
nohup python3 /root/pushbot/apps/LuckyMonami.py &
nohup python3 /root/pushbot/apps/WinFrenzy.py &
nohup python3 /root/pushbot/apps/AladdinLamp.py &
nohup python3 /root/pushbot/apps/CherryBomb.py &
nohup python3 /root/pushbot/apps/ConquestPower.py &
nohup python3 /root/pushbot/apps/DungeonsaAndRiches.py &
nohup python3 /root/pushbot/apps/TreasureRush.py &
nohup python3 /root/pushbot/apps/Castleflight.py &
nohup python3 /root/pushbot/apps/MoneyMey.py &
nohup python3 /root/pushbot/apps/ArmofHeroes.py &
nohup python3 /root/pushbot/apps/VHUI.py &
nohup python3 /root/pushbot/apps/VV_Hu_Iceman.py &
nohup python3 /root/pushbot/apps/R_SK_Dubai_2495.py &
nohup python3 /root/pushbot/apps/W_BE_Lemon_2560.py &
nohup python3 /root/pushbot/apps/W_BE_Victory_2567.py &
nohup python3 /root/pushbot/apps/VV_CZ_Iceman_2558.py &
nohup python3 /root/pushbot/apps/VV_RO_Iceman_2558.py &
nohup python3 /root/pushbot/apps/W_BE_Lemon_2569.py &
nohup python3 /root/pushbot/apps/VV_RO_Iceman_2570.py &
nohup python3 /root/pushbot/apps/VV_RO_Lemon_2579.py &
nohup python3 /root/pushbot/apps/S_CZ_Dem_2580.py &
nohup python3 /root/pushbot/apps/VV_NO_Victory_2583.py &
nohup python3 /root/pushbot/apps/S_CZ_Iceman_2585.py &
nohup python3 /root/pushbot/apps/CC_SK_Anelin_2598.py &
nohup python3 /root/pushbot/apps/CC_SK_Anelin_2599.py &
nohup python3 /root/pushbot/apps/CC_AT_Anelin_2602.py &
nohup python3 /root/pushbot/apps/CC_KR_Anelin_2603.py &
nohup python3 /root/pushbot/apps/CC_IE_Dubai_2604.py &
nohup python3 /root/pushbot/apps/CC_AT_Dubai_2605.py &
nohup python3 /root/pushbot/apps/CC_KR_Anelin_2606.py &
nohup python3 /root/pushbot/apps/CC_AT_Graf_2607.py &
nohup python3 /root/pushbot/apps/CC_NZ_Graf_2608.py &
nohup python3 /root/pushbot/apps/CC_CA_Lemon_2612.py &
nohup python3 /root/pushbot/apps/V777_UA_Iceman_2616.py &
nohup python3 /root/pushbot/apps/V777_UA_Iceman_2621.py &
nohup python3 /root/pushbot/apps/CaptainCooks.py &
nohup python3 /root/pushbot/apps/CC_SK_Dubai_2626.py &
nohup python3 /root/pushbot/apps/C_UA_Lemon_2629.py &
nohup python3 /root/pushbot/apps/C_UA_Lemon_2630.py &
nohup python3 /root/pushbot/apps/C_UA_Lemon_2631.py &
nohup python3 /root/pushbot/apps/GPT_GooglePlay_2647.py &
nohup python3 /root/pushbot/apps/EgyptBonus.py &
nohup python3 /root/pushbot/apps/CV_UA_Dem_2693.py &
nohup python3 /root/pushbot/apps/KV_UA_IceMan_2688.py &
nohup python3 /root/pushbot/apps/KV_UA_IceMan_2689.py &
nohup python3 /root/pushbot/apps/KV_UA_Dem_2684.py &
nohup python3 /root/pushbot/apps/W_IT_Graf_2682.py &
nohup python3 /root/pushbot/apps/W_BE_Graf_2683.py &
nohup python3 /root/pushbot/apps/CC_SK_Dubai_2679.py &
nohup python3 /root/pushbot/apps/CC_SK_Dubai_2680.py &
nohup python3 /root/pushbot/apps/CC_SK_Dubai_2681.py &
nohup python3 /root/pushbot/apps/DiamondCave.py &
nohup python3 /root/pushbot/apps/CavemanJumper.py &
nohup python3 /root/pushbot/apps/EF_2787.py &
nohup python3 /root/pushbot/apps/GG_2829.py &
nohup python3 /root/pushbot/apps/WR_2889.py &
nohup python3 /root/pushbot/apps/GC_2857.py &